/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Product service. Represents a row in the &quot;sb_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.ProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.ProductImpl}.
 * </p>
 *
 * @author Michael
 * @see Product
 * @see com.test.model.impl.ProductImpl
 * @see com.test.model.impl.ProductModelImpl
 * @generated
 */
public interface ProductModel extends BaseModel<Product> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this product.
	 *
	 * @return the product ID of this product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product.
	 *
	 * @param productId the product ID of this product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the product name of this product.
	 *
	 * @return the product name of this product
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product.
	 *
	 * @param productName the product name of this product
	 */
	public void setProductName(String productName);

	/**
	 * Returns the weight of this product.
	 *
	 * @return the weight of this product
	 */
	public int getWeight();

	/**
	 * Sets the weight of this product.
	 *
	 * @param weight the weight of this product
	 */
	public void setWeight(int weight);

	/**
	 * Returns the manufacture date of this product.
	 *
	 * @return the manufacture date of this product
	 */
	public Date getManufactureDate();

	/**
	 * Sets the manufacture date of this product.
	 *
	 * @param manufactureDate the manufacture date of this product
	 */
	public void setManufactureDate(Date manufactureDate);

	/**
	 * Returns the date of sale of this product.
	 *
	 * @return the date of sale of this product
	 */
	public Date getDateOfSale();

	/**
	 * Sets the date of sale of this product.
	 *
	 * @param dateOfSale the date of sale of this product
	 */
	public void setDateOfSale(Date dateOfSale);

	/**
	 * Returns the baker name of this product.
	 *
	 * @return the baker name of this product
	 */
	@AutoEscape
	public String getBakerName();

	/**
	 * Sets the baker name of this product.
	 *
	 * @param bakerName the baker name of this product
	 */
	public void setBakerName(String bakerName);

	/**
	 * Returns the price of this product.
	 *
	 * @return the price of this product
	 */
	public double getPrice();

	/**
	 * Sets the price of this product.
	 *
	 * @param price the price of this product
	 */
	public void setPrice(double price);

	/**
	 * Returns the office of this product.
	 *
	 * @return the office of this product
	 */
	@AutoEscape
	public String getOffice();

	/**
	 * Sets the office of this product.
	 *
	 * @param office the office of this product
	 */
	public void setOffice(String office);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.test.model.Product product);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.test.model.Product> toCacheModel();

	@Override
	public com.test.model.Product toEscapedModel();

	@Override
	public com.test.model.Product toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}